[package]
name = "waylandkb"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
gtk = { package = "gtk4", version = "0.9" }
gtk4-layer-shell = "0.4"
libc = "0.2"
tempfile = "3"
wayland-client = { version = "0.31", features = ["system"] }
wayland-protocols = { version = "0.32", features = ["client", "staging"] }
wayland-protocols-misc = { version = "0.3", features = ["client"] }
